repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the Ruff linter.
      - id: ruff
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.4
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix